// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor.DAL;

#nullable disable

namespace ServidorSocketPrimary.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Servidor.Models.Reservaciones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Reservaciones");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Cedula = "402-1274726-1",
                            Fecha = new DateTime(2022, 9, 28, 16, 31, 28, 15, DateTimeKind.Local).AddTicks(4356),
                            Mesa = "Mesa 1",
                            Nombre = "Juancito Francisco"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
